### PR TITLE
distutils -> setuptools

### PR DESCRIPTION
**Pull request by yasoob**
Fixes the "Unknown distribution option: 'install_requires'" error while running `make install`. 

distribute is deprecated according to http://pythonhosted.org/distribute/:

    Distribute is a deprecated fork of the Setuptools project.

    Since the Setuptools 0.7 release, Setuptools and Distribute have merged and
    Distribute is no longer being maintained. All ongoing effort should reference the
    Setuptools project and the Setuptools documentation.

### CODE REVIEW

**Comment by sambayless** [comment]
Thanks for submitting a patch!
Can I ask which OS/platform/distribution you've tested this on? 
I'm concerned that if I merge this patch in, it might be the case that older systems will no longer be able to install the python API correctly (I'm not sure yet if that is the case or now).

**Comment by yasoob** [comment]
I tested this on Mac OS High Sierra with Python 3.7.

**Comment by yasoob** [comment]
I also successfully installed it on Ubuntu 18.04.1 LTS with this patch. Python version 3.6.7.

**Comment by sambayless** [comment]
Hmm, I also need to maintain support for older distributions.
What if we instead did:
```
try:
   from setuptools import setup
except ImportError as e:
   from distutils.core import setup
```

(As seen here: https://stackoverflow.com/a/25359853)

**Comment by yasoob** [comment]
Yeah that seems reasonable. 👍

**Pull request merged**
